### ISSUE TITLE
Handle `out of order` shares in the data square

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/rsmt2d#191] opened 2023-06-22 12:25 UTC
Based on [this](https://github.com/celestiaorg/celestia-node/issues/2377) we may run in a situation when shares will be out of order in the dataSquare. In this case, we will not be able to compute the Merkle root of row or col and reconstruction fails. To handle such error properly we need to get these shares+indexes of Merkel Roots of the opposite axis(to build a Merkle Proof against them). If Merkle Roots for both row/col can't be computed, then we should receive an error that data is not available.

**Comment by musalbas** [comment] 2023-06-23 15:32
Is this not contradictory to [this comment](https://github.com/celestiaorg/celestia-node/issues/2377) from @adlerjohn? Verification logic doesn't happen in rsmt2d.

>We don't need a different data structure, we just need additional codepaths in the verification logic to handle the two additional cases described in OP. The data structure of the proof can remain the same.

**Comment by staheri14** [comment] 2023-06-26 22:34
@musalbas From what I understand, this issue is not about implementing the verification logic in the rsmt2d, rather it is about adding support for detecting situations where the root construction has failed due to unordered leaves and returning an error with enough information e.g., the index of unordered shares (column and row) to the caller, likely as part of the [ErrByzantineData](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L42). Then the caller will take care of crafting a proper proof.

**Comment by musalbas** [comment] 2023-06-26 22:44
I don't think that can be handled directly in rsmt2d, because rsmt2d does not assume that the square uses a namespaced Merkle tree.

I also don't know if that's what's being requested, but we should clarify. cc @adlerjohn

**Comment by staheri14** [comment] 2023-06-26 22:58
> I don't think that can be handled directly in rsmt2d, because rsmt2d does not assume that the square uses a namespaced Merkle tree.


As far as I can say, it has access to the errors returned by the underlying tree construction function, based on which can populate the [ErrByzantineData](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L42).


Below are two approaches that I see to this issue (considering that what I have described in this [comment](https://github.com/celestiaorg/rsmt2d/issues/191#issuecomment-1608411388) is what this issue is aimed for). 
1. Attempt to compute the root using [computeSharesRoot](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L411). Based on the returned error in [here](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L294), which should include relevant information about the unordered shares, populate the [ErrByzantineData](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L42) structure and return it.
2. Perform a sanity check on the available shares and ensure that their namespaces are sorted before attempting to repair the square and compute the root (i.e., the [Repair](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L67) function). This can be done as part of [prerepairSanityCheck](https://github.com/celestiaorg/rsmt2d/blob/9df814cc86ead030e1ec8834579259734380c236/extendeddatacrossword.go#L334). This approach offers multiple benefits:
a) The check is performed only on the shares for which we have an inclusion proof, rather than on the ones computed by erasure coding and repairing.
b) It saves computation time for hashing by avoiding the attempt to construct the root.

**Comment by musalbas** [comment] 2023-06-27 08:58
I don't think it can be done in `prerepairSanityCheck`, because new unordered leafs may be discovered in the middle of the `solveCrossword` loop when new rows or columns are reconstructed.

As for (1), are you proposing to add a new error field to `ErrByzantineData`?

**Comment by vgonkivs** [comment] 2023-06-27 09:47
Am I correct that in the case of out-of-order shares in the particular row/col, we will not be able to get the subtree roots and build the proof against this particular row/col? If so, then I guess in the node we can add a statement, during BEFP construction, that checks the subtree roots and re-requests the orthogonal axis.

**Comment by musalbas** [comment] 2023-06-27 09:50
The issue is that you might not be able to get the subtree root not only if the shares are out of order, but if the row that the BEFP for is simply erasure coded incorrectly, and thus does not match the subtree root. In that case, you need to use the inclusion proofs that the node already downloaded via sampling.

**Comment by vgonkivs** [comment] 2023-06-27 10:03
But does not ErrByzantineData [store](https://github.com/celestiaorg/rsmt2d/blob/a5abc274592816034b5a5dac74c6aca844895081/extendeddatacrossword.go#L154) only [sampled shares](https://github.com/celestiaorg/rsmt2d/blob/a5abc274592816034b5a5dac74c6aca844895081/extendeddatacrossword.go#L136) and not the rebuilt ones?

**Comment by musalbas** [comment] 2023-06-27 10:16
I believe ErrByzantineData returns the shares of the "last known good" square, which can include rebuilt rows and columns. This is because you may need to use shares from rebuilt rows and columns in the BEFP.

Basically, I believe the rule for choosing what proof should be used for a BEFP share should be:
1. If a share is inside a fully and validly reconstructed row or column, then you can generate an inclusion proof from that row or column.
2. Otherwise, you need to use Merkle inclusion proofs that the full node received from other nodes via sampling. Example: consider a square where all erasure coding quadrants (quadrants 2, 3, 4) contain garbage data.

**Comment by staheri14** [comment] 2023-06-27 16:53
I have read the comments and will get back soon to this thread.

**Comment by musalbas** [comment] 2023-06-28 23:46
AFAIK, we do not need to modify any fields in `ErrByzantineData`, so we don't need to add the index of unordered shares, nor do we need to return the newly repaired shares for an incorrect row/col root.

The only thing needed, is to see that the row root of the recomputed row does not match the row root that was committed to in the block header, because when we recompute the row root with the nmt library, it should return `err` out due to shares being out of order, and `err` will not match the committed row root in the block header.

See [this comment](https://github.com/celestiaorg/celestia-node/issues/2377#issuecomment-1609316238) for an explanation of why:

> > During the reconstruction process, if there are two shares that are out of order, then we should still be able to create an inclusion proof to half of the shares in that row or col using either the row or column roots. If the square is available, then this will always be the case.
> 
> Let's think about the end-to-end flow of sampling and reconstruction. Note that shares being out of order is not the only case where you cannot recompute a row or column root; this would also be the case if any reconstructed shares do not match the row or column root. We can conceptually treat an out-of-order share as the same as a recomputed share that does not match the row or column root.
> 
> Firstly, it should not be possible to sample a share that has any sibling nodes that are out of order, because the proof NMT verification will fail when it tries to reconstruct the root (due to a mismatch when calculating min and max nid).
> 
> Next, we should consider [this rule](https://github.com/celestiaorg/rsmt2d/issues/191):
> 
> > Basically, I believe the rule for choosing what proof should be used for a BEFP share should be:
> > 
> > 1. If a share is inside a fully and validly reconstructed row or column, then you can generate an inclusion proof from that row or column.
> > 2. Otherwise, you need to use Merkle inclusion proofs that the full node received from other nodes via sampling. Example: consider a square where all erasure coding quadrants (quadrants 2, 3, 4) contain garbage data that does not match the actual row or column roots.
> 
> From the above, it doesn't seem to me like we need to create inclusion proofs ourselves in rows/cols with shares out of order, due to (2). Does that seem right @adlerjohn @evan-forbes?

---

Implementation wise, the only thing I'm unsure of is if  `err` is be bubbled up in `getRowRoot`, and how `solveCrossword` behaves if there's an error, which should be reviewed. Seems like the [tree's err is just returned](https://github.com/celestiaorg/rsmt2d/blob/master/extendeddatacrossword.go#L326), when the desired behavior should actually be to return `ErrByzantineData`, so that should be discussed. Either we change the err returned to be `ErrByzantineData` (which might not be clean, not sure we can assume that is good behaviour for all trees, or if NMT should actually return nil on unordered shares).

**Comment by musalbas** [comment] 2023-06-28 23:48
By the way, we also need to consider how this would work for column roots, which I believe follow different namespace rules.

**Comment by adlerjohn** [comment] 2023-06-29 00:39
> we do not need to modify any fields in `ErrByzantineData`

Agreed, the error already contains all the necessary information from rsmt2d that node needs.

> Implementation wise, the only thing I'm unsure of is if err is be bubbled up in getRowRoot, and how solveCrossword behaves if there's an error, which should be reviewed. Seems like the [tree's err is just returned](https://github.com/celestiaorg/rsmt2d/blob/master/extendeddatacrossword.go#L326), when the desired behavior should actually be to return ErrByzantineData, so that should be discussed. Either we change the err returned to be ErrByzantineData (which might not be clean, not sure we can assume that is good behaviour for all trees, or if NMT should actually return nil on unordered shares).

Good catch, and I think that's the missing piece. IMO rsmt2d should return an `ErrByzantineData` error if the tree construction fails for whatever reason. No need to return the tree's error.

**Comment by adlerjohn** [comment] 2023-06-29 00:45
> I believe ErrByzantineData returns the shares of the "last known good" square, which can include rebuilt rows and columns. This is because you may need to use shares from rebuilt rows and columns in the BEFP.
> 
> Basically, I believe the rule for choosing what proof should be used for a BEFP share should be:
> 
>     1. If a share is inside a fully and validly reconstructed row or column, then you can generate an inclusion proof from that row or column.
> 
>     2. Otherwise, you need to use Merkle inclusion proofs that the full node received from other nodes via sampling. Example: consider a square where all erasure coding quadrants (quadrants 2, 3, 4) contain garbage data that does not match the actual row or column roots.

This is the correct intuition: either the shares in the `ErrByzantineData`---when extended---are committed to in the row/col root, or they're not. If they're not then by construction the shares are either on a complete col/row or they were obtained from sampling.

**Comment by vgonkivs** [comment] 2023-06-29 07:36
Agree with Mustafa and John that we do not need to modify fields in `ErrByzantineData` as we have a set of all the necessary information to build the BEFP and the out-of-order shares we will detect during [nmt tree creation](https://github.com/celestiaorg/celestia-node/blob/4d986940d662649eba4b0d3daa85268318204ff2/share/eds/byzantine/bad_encoding.go#L175) in BEFP validation.

**Comment by staheri14** [comment] 2023-06-29 20:47
Also, agreed with the point that `ErrByzantineData` is sufficient for the BEFP and doesn't need any change. 

> > Implementation wise, the only thing I'm unsure of is if err is be bubbled up in getRowRoot, and how solveCrossword behaves if there's an error, which should be reviewed. Seems like the [tree's err is just returned](https://github.com/celestiaorg/rsmt2d/blob/master/extendeddatacrossword.go#L326), when the desired behavior should actually be to return ErrByzantineData, so that should be discussed. Either we change the err returned to be ErrByzantineData (which might not be clean, not sure we can assume that is good behaviour for all trees, or if NMT should actually return nil on unordered shares).

> Good catch, and I think that's the missing piece. IMO rsmt2d should return an ErrByzantineData error if the tree construction fails for whatever reason. No need to return the tree's error. This doesn't even need to assume an underlying NMT; any tree construction failing is sufficient for the algorithm to fail.

Also, agree with this.

**Comment by staheri14** [comment] 2023-06-29 21:18
FYI: I'm moving forward with the implementation of the following solution in rsmt2d:  if the tree construction fails for a row or column, during the repair process, an `ErrByzantineData` should be populated and returned.

**Comment by musalbas** [comment] 2023-06-30 09:02
>Implementation wise, the only thing I'm unsure of is if err is be bubbled up in getRowRoot, and how solveCrossword behaves if there's an error, which should be reviewed. Seems like the [tree's err is just returned](https://github.com/celestiaorg/rsmt2d/blob/master/extendeddatacrossword.go#L326), when the desired behavior should actually be to return ErrByzantineData, so that should be discussed. Either we change the err returned to be ErrByzantineData (which might not be clean, not sure we can assume that is good behaviour for all trees, or if NMT should actually return nil on unordered shares).

This is related to `ErrByzantineData.Shares are not filled` (p11) in Informal's audit report.

**Comment by musalbas** [comment] 2023-06-30 09:10
Related, potentially the same issue: https://github.com/celestiaorg/rsmt2d/issues/178

**Comment by staheri14** [comment] 2023-07-03 21:22
Thanks for mentioning the https://github.com/celestiaorg/rsmt2d/issues/178. 
It is relevant, however, they are addressing different problems. Nevertheless, the solution to the current issue would ultimately need to consume the fix to https://github.com/celestiaorg/rsmt2d/issues/178. That is, when preparing `ErrByzantineData` due to failure in root calculation (i.e., the current issue) for a newly completed orthogonal axis, the `ErrByzantineData`  should also include the newly rebuilt share.

**Comment by staheri14** [comment] 2023-07-03 21:31
Update: I actually need to also address #178 as part of addressing the current issue. @rootulp Have you started on https://github.com/celestiaorg/rsmt2d/issues/178, if not, I can address it as part of this issue.

**Closed** 2023-07-12 17:07 UTC
Labels: enhancement
